### Numpy
- 파이썬에서 제공하는 list, tuple로는 행렬에 관련된 작업을 하기가 어려움
- 행렬에 관련된 연산을 위해 제공하는 라이브러리
- 수학에서의 행렬에 대한 작업을 할 수 있음

In [2]:
import numpy as np

In [74]:
# 리스트
list1 = [10, 20, 30, 40, 50]
list2 = [60, 70, 80, 90, 100]

In [75]:
# 더히기
list3 = list1 + list2
list3

[10, 20, 30, 40, 50, 60, 70, 80, 90, 100]

In [76]:
# 곱하기
list4 = list1 * 3
list4

[10, 20, 30, 40, 50, 10, 20, 30, 40, 50, 10, 20, 30, 40, 50]

In [77]:
# 뺄셈
list5 = list1 - list2
list5

TypeError: unsupported operand type(s) for -: 'list' and 'list'

In [86]:
# ndarray
array1 = np.array([10, 20, 30, 40, 50])
array2 = np.array([60, 70, 80, 90, 100])

In [87]:
# 더하기
array3 = array1 + array2
array3

array([ 70,  90, 110, 130, 150])

In [88]:
# 곱하기
array4 = array1 * 3
array4

array([ 30,  60,  90, 120, 150])

In [89]:
# 뺄셈
array5 = array1 - array2
array5

array([-50, -50, -50, -50, -50])

### 행렬생성
- 리스트나 튜플을 이용하여 생성
- 생성된 행렬의 타입은 다차원 행렬이라는 의미로 ndarray로 불린다

In [78]:
# 1차원 리스트
list1 = [10, 20, 30, 40, 50]

# 1차원 행렬(함수 안에 리스트나 튜플을 넣어준다)
array1 = np.array([10, 20, 30, 40, 50])

print(list1)
print(array1)

display(list1)
display(array1)

[10, 20, 30, 40, 50]
[10 20 30 40 50]


[10, 20, 30, 40, 50]

array([10, 20, 30, 40, 50])

In [79]:
print(type(list1))
print(type(array1))

<class 'list'>
<class 'numpy.ndarray'>


In [80]:
# 2차원 리스트
list2 = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

# 2차원 행렬
array2 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(list2)
print(array2)

display(list2)
display(array2)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### 행렬과 데이터 타입의 관계

In [81]:
list1 = [True, 100, 11.11, '문자열']

# ndarray는 같은 타입의 값만 담을 수 있음
# 다양한 타입의 값이 섞여져 있을 경우 더 많은 값의 종류를
# 표현할 수 있는 형태로 변환
# 논리형 -> 정수 -> 실수 -> 문자열

array1 = np.array([True, 100, 11.11, '문자열'])

display(list1)
display(array1)

[True, 100, 11.11, '문자열']

array(['True', '100', '11.11', '문자열'], dtype='<U32')

In [82]:
# 행렬의 타입을 확인
array2 = np.array([0, 1, 2, 3, 4])
array3 = np.array([11, 11.11, 22.22, 33.33])

print(type(array2))
print(array3.dtype)

<class 'numpy.ndarray'>
float64


In [83]:
# 행렬을 생성할때 타입을 설정할 수 있다.
# 정수: int, 실수: float, 논리: bool, 문자열: str
array4 = np.array([0, 1, 2, 3, 4], dtype='float')
array5 = np.array([0, 1, 2, 3, 4])

print(array4.dtype)
print(array5.dtype)

float64
int64


In [84]:
array6 = np.array(['1', '2', '3'], dtype='int')

print(array6)
print(array6.dtype)

[1 2 3]
int64


In [85]:
array7 = np.array(['홍길동', '김길동', '최길동'], dtype='int')

print(array7)
print(array7.dtype)

ValueError: invalid literal for int() with base 10: '홍길동'

In [90]:
array8 = np.array(['홍길동', '김길동'], dtype='bool')

print(array8)
print(array8.dtype)

[ True  True]
bool


In [91]:
array9 = np.array(['홍길동', '김길동'], dtype='bool')

print(array9)
print(array9.dtype)

array10 = np.array(['True', 'False', 'True', 'False'], dtype='bool')

print(array10)
print(array10.dtype)

[ True  True]
bool
[ True  True  True  True]
bool


In [92]:
array11 = np.array([11.11, 22.22, 33.33], dtype='int')

print(array11)
print(array11.dtype)

[11 22 33]
int64


In [93]:
# 이미 생성되어 있는 행렬의 값을 추출하여 다른 타입으로 행렬을 생성
# 정수: int, 실수: float, 논리: bool, 문자열: str
array12 = array4.astype('str')

print(array12)
print(array12.dtype)

['30' '60' '90' '120' '150']
<U21


### 행렬 생성 함수

In [94]:
# 값을 정해주면서 생성
# 값은 리스트나 튜플 등과 같이 순서를 가지고 값을 관리하는 요소를 지정
array1 = np.array([10, 20, 30, 40, 50])
array1

array([10, 20, 30, 40, 50])

In [96]:
# 딕셔너리로 행렬 생성
d1 = {
    'a1':100,
    'a2':22.22,
    'a3':True,
    'a4':'문자열',
}

# 딕셔너리를 원소로 가지고 있는 행렬이 생성됨
array2 = np.array(d1)
display(array2)

# 딕셔너리
array3 = np.array(list(d1.values()))
display(array3)
display(array3.dtype)

array({'a1': 100, 'a2': 22.22, 'a3': True, 'a4': '문자열'}, dtype=object)

array(['100', '22.22', 'True', '문자열'], dtype='<U32')

dtype('<U32')

In [99]:
# 0 행렬
# 원소가 0으로 채워진 행렬
# 0이 5개 있는 1차원 배열
array4 = np.zeros(5)
display(array4)

# 0으로 채워진 3행 4열 2차원 행렬
# 행과 열의 수를 리스트로 지정해 줌
array5 = np.zeros([3, 4])
display(array5)

array([0., 0., 0., 0., 0.])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [101]:
# 1이 5개 있는 1차원 행렬
array6 = np.ones(5)
display(array6)

# 1로 채워진 3행 4열 2차원 행렬
array7 = np.ones([3, 4])
display(array7)

array([1., 1., 1., 1., 1.])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [103]:
# n으로 채워진 행렬
# 7이 5개 있는 1차원 행렬
array8 = np.full(5, 7)
display(array8)

# 7로 채워진 3행 4열의 2차원 행렬
array9 = np.full([3, 4], 7)
display(array9)

array([7, 7, 7, 7, 7])

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [104]:
# 행렬을 만들고 아무값도 넣어주지 않는다.
# 빠르게 행렬을 생성하고 싶을때 사용함
# 단, 값을 채우는 작업을 해주지 않기 때문에 행렬 사용 전에
# 반드시 값을 채워줘야 함.

# 5개까지 1차원 행렬
array10 = np.empty(5)

# 3행 4열짜리 2차원 행렬
array11 = np.empty([3, 4])

display(array10)
display(array11)

array([3.5e-323, 3.5e-323, 3.5e-323, 3.5e-323, 3.5e-323])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [105]:
# 특정 범위를 가진 행렬을 생성
# 0~6-1까지 1씩 증가하는 행렬
array12 = np.arange(6)
array12

array([0, 1, 2, 3, 4, 5])

In [106]:
# 3~13-1까지 1씩 증가하는 행렬을 생성
array13 = np.arange(3, 13)
array13

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [107]:
# 3~13-1까지 2씩 증가
array14 = np.arange(3, 13, 2)
array14

array([ 3,  5,  7,  9, 11])

### 인덱싱과 슬라이싱
- 인덱싱: 값 하나를 가져오는 것
- 슬라이싱: 원하는 부분의 값을 가져오는 것

In [108]:
# 1차원
list1 = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
array1 = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

In [110]:
# 값 하나를 가져온다. 0부터 1씩 증가하는 위치값
print(list1[0])
print(array1[0])
print(list1[1])
print(array1[1])

10
10
20
20


In [111]:
# 마이너스 인덱스, 뒤에서부터.
print(list1[-1])
print(array1[-1])
print(list1[-2])
print(array1[-2])

100
100
90
90


In [112]:
# 위치값 2~6-1까지
print(list1[2:6])
print(array1[2:6])

[30, 40, 50, 60]
[30 40 50 60]


In [113]:
# 위치값 처음~6-1까지
print(list1[:6])
print(array1[:6])

[10, 20, 30, 40, 50, 60]
[10 20 30 40 50 60]


In [114]:
# 위치값 2~끝까지
print(list1[2:])
print(array1[2:])

[30, 40, 50, 60, 70, 80, 90, 100]
[ 30  40  50  60  70  80  90 100]


In [115]:
list2d = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

array2d = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [120]:
# 2행 3열 데이터를 가져온다.
print(list2d[1][2])
print(array2d[1][2])
print(array2d[1,2])

6
6
6


In [123]:
# 위치값 1~3-1 행, 1~3-1열의 데이터를 가져옴
display(list2d[1:3][1:3])
display(array2d[1:3][1:3])
display(array2d[1:3, 1:3][]

[[7, 8, 9]]

array([[7, 8, 9]])

array([[5, 6],
       [8, 9]])

In [8]:
# 원하는 것만 가져오는 테스트 위해 행렬을 다시 만듬
array1 = np.array([10, 20, 30, 40, 50])

In [9]:
# 위치값 0, 1, 4에 해당하는 것만 가져옴
array2 = array1[[0, 1, 4]]
print(array2)

[10 20 50]


In [10]:
# True와 False로 구성된 리스트를 넣어서 값을 가져옴.
# True 자리에 해당하는 값만 추출하여 줌
# 행렬의 원소의 개수와 맞지 않으면 오류가 발생함.
array3 = array1[[True, False, True, False, True]]
array3

array([10, 30, 50])