In [1]:
import numpy as np

### 행렬의 산술연산

In [2]:
# 행렬과 행렬의 산술연산
# 두 행렬의 행과 열의 개수가 일치해야 함.
# 두 행렬의 원소를 1:1 대응하여 연산하고 그 결과를
# 가지고 있는 행렬을 생성하여 반환

array1 = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90],
])

array2 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
])

In [3]:
a1 = array1 + array2
a2 = array1 - array2
a3 = array1 * array2
a4 = array1 // array2

display(a1)
display(a2)
display(a3)
display(a4)

array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99]])

array([[ 9, 18, 27],
       [36, 45, 54],
       [63, 72, 81]])

array([[ 10,  40,  90],
       [160, 250, 360],
       [490, 640, 810]])

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [4]:
# 행렬과 그 숫자와의 연산
# 행렬의 각 원소를 지정한 숫자와 연산하고
# 그 결과ㅓ를 담은 행렬을 반환

a1 = array1 + 10
a2 = array1 - 10
a3 = array1 * 10
a4 = array1 // 10

display(a1)
display(a2)
display(a3)
display(a4)

array([[ 20,  30,  40],
       [ 50,  60,  70],
       [ 80,  90, 100]])

array([[ 0, 10, 20],
       [30, 40, 50],
       [60, 70, 80]])

array([[100, 200, 300],
       [400, 500, 600],
       [700, 800, 900]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
# 관계연산자
a1 = array1 >= 50
a1

array([[False, False, False],
       [False,  True,  True],
       [ True,  True,  True]])

In [6]:
# 1~100-1까지 담고 있는 ndarray 생성
array1 = np.arange(1, 100)
print(array1)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]


In [8]:
# 3으로 나눈 나머지를 구함
a1 = array1 % 3
a1

array([1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1,
       2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2,
       0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0,
       1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1,
       2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0])

In [9]:
# 3으로 나눈 나머지가 0인가?
a2 = a1 == 0
a2

array([False, False,  True, False, False,  True, False, False,  True,
       False, False,  True, False, False,  True, False, False,  True,
       False, False,  True, False, False,  True, False, False,  True,
       False, False,  True, False, False,  True, False, False,  True,
       False, False,  True, False, False,  True, False, False,  True,
       False, False,  True, False, False,  True, False, False,  True,
       False, False,  True, False, False,  True, False, False,  True,
       False, False,  True, False, False,  True, False, False,  True,
       False, False,  True, False, False,  True, False, False,  True,
       False, False,  True, False, False,  True, False, False,  True,
       False, False,  True, False, False,  True, False, False,  True])

In [11]:
array2 = array1[a2]
array2

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51,
       54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [12]:
array3 = array1[array1 % 3 == 0]
array3

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51,
       54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

### 행렬 연산

In [13]:
array1 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [14]:
# 전치행렬
# 행 -> 열, 열 -> 행
array2 = array1.transpose()
array2

array([[1, 4],
       [2, 5],
       [3, 6]])

In [15]:
array3 = array1.T
array3

array([[1, 4],
       [2, 5],
       [3, 6]])

In [16]:
# 행렬곱(내적) 연산
display(array1)
display(array2)

array4 = array1.dot(array2)
display(array4)

array([[1, 2, 3],
       [4, 5, 6]])

array([[1, 4],
       [2, 5],
       [3, 6]])

array([[14, 32],
       [32, 77]])

### 행렬의 구조를 변경

In [17]:
# 1차원 행렬을 생성
array1 = np.arange(15)
array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [18]:
# 1차원 -> 2차원
array2 = array1.reshape(3, 5)
array2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [19]:
# 원소가 15개인 1차원 행렬을 4행 5열짜리 행렬로 변환
array3 = array1.reshape(4, 5)
array3

ValueError: cannot reshape array of size 15 into shape (4,5)

In [20]:
# -1: 행이나 열의 수에 지정하면 다른쪽 값을 보고 자동 설정됨.
# 1개만 설정 가능
array4 = array1.reshape(-1, 5)
array4

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [22]:
# 2차원 -> 1차원
# 총 원소의 개수를 지정함. 부족하거나 많게 지정하면 오류가 발생함
array5 = array4.reshape(15)
array5

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [23]:
array6 = array4.reshape(-1)
array6

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [24]:
# 행렬의 차원수
print(array4.ndim)
print(array6.ndim)

2
1


In [26]:
# 행렬의 행과 열의 수
print(array4.shape)
print(array6.shape)

(3, 5)
(15,)


In [29]:
# 전체 원소의 개수
# 2차원인 경우는 행의 수가 반환됨
print(len(array4))
print(len(array6))

# size는 원소의 총개수를 구해 반환됨
print(array4.size)
print(array6.size)

3
15
15
15


### 통계함수

In [30]:
array1 = np.arange(15).reshape(3, 5)
array1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [31]:
# 행렬을 통한 통계 계산
a1 = array1.mean()
a2 = array1.max()
a3 = array1.min()

print(a1)
print(a2)
print(a3)

7.0
14
0


In [32]:
# numpy가 제공하는 함수
a1 = np.mean(array1)
a2 = np.max(array1)
a3 = np.min(array1)

print(a1)
print(a2)
print(a3)

7.0
14
0


In [34]:
# axis: 어떠한 작업의 기준 혹은 작업을 위해 데이터를 묶는 기준을 설정함
# 0: 행기준, 1: 열기준

# 열별 통계
a1 = array1.mean(axis=0)
# 행별 통계
a2 = array1.mean(axis=1)

print(a1)
print(a2)

[5. 6. 7. 8. 9.]
[ 2.  7. 12.]


### 로또 번호 추첨하기

In [35]:
# 1~45까지 가지고 있는 행렬을 생성
array1 = np.arange(1, 46)
array1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45])

In [37]:
for _ in range(10):
    # 랜덤하게 섞은 행렬을 생성
    array2 = np.random.permutation(array1)
    # 앞에서부터 6개를 추출
    array3 = array2[:6]
    # 행렬 자체를 정렬
    array3.sort()
    display(array3)

array([18, 21, 24, 26, 32, 36])

array([17, 27, 29, 30, 38, 39])

array([13, 19, 21, 24, 37, 39])

array([11, 13, 20, 29, 35, 40])

array([ 4,  7, 19, 23, 31, 40])

array([ 9, 16, 21, 25, 38, 41])

array([ 4,  6, 20, 32, 39, 43])

array([ 5, 10, 19, 33, 38, 40])

array([ 3, 14, 19, 35, 38, 44])

array([ 8, 13, 14, 16, 25, 36])